
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/proj-courses-s25-03
owner: ucsb-cs156-s25
repo_name: proj-courses-s25-03
pull_requests: [{"author":{"id":"U_kgDOB2-VXA","is_bot":false,"login":"daisyzhongg","name":""},"headRefName":"dz-implement-weekly-view","number":45,"title":"Implement weekly view event","url":"https://github.com/ucsb-cs156-s25/proj-courses-s25-03/pull/45"},{"author":{"id":"U_kgDOBvSp8w","is_bot":false,"login":"saahasburicha","name":"Saahas Buricha"},"headRefName":"pc-placeholder-GESearchpage","number":43,"title":"added placeholder and added routes for GESearch","url":"https://github.com/ucsb-cs156-s25/proj-courses-s25-03/pull/43"},{"author":{"id":"MDQ6VXNlcjY1OTQ0NzE3","is_bot":false,"login":"klai890","name":"Karena Lai"},"headRefName":"kl-ge-areas-dropdown","number":42,"title":"Create GE areas dropdown component","url":"https://github.com/ucsb-cs156-s25/proj-courses-s25-03/pull/42"},{"author":{"id":"MDQ6VXNlcjY1OTQ0NzE3","is_bot":false,"login":"klai890","name":"Karena Lai"},"headRefName":"kl-ge-areas-fixtures","number":41,"title":"Create fixtures for the GE area dropdown component","url":"https://github.com/ucsb-cs156-s25/proj-courses-s25-03/pull/41"},{"author":{"id":"U_kgDOCVHShQ","is_bot":false,"login":"xanxp","name":"Xin Ping Xandra Wong"},"headRefName":"xw-GET-APIEndpoint-GEArea","number":39,"title":"xw - add endpoint to return array of GE Areas","url":"https://github.com/ucsb-cs156-s25/proj-courses-s25-03/pull/39"},{"author":{"id":"MDQ6VXNlcjY1OTQ0NzE3","is_bot":false,"login":"klai890","name":"Karena Lai"},"headRefName":"kl-paginate-jobs-frontend","number":36,"title":"Paginate Jobs frontend","url":"https://github.com/ucsb-cs156-s25/proj-courses-s25-03/pull/36"},{"author":{"id":"MDQ6VXNlcjY1OTQ0NzE3","is_bot":false,"login":"klai890","name":"Karena Lai"},"headRefName":"kl-paginate-jobs-frontend-filter-component","number":31,"title":"Add filter component for pagination of the Jobs frontend","url":"https://github.com/ucsb-cs156-s25/proj-courses-s25-03/pull/31"},{"author":{"id":"MDQ6VXNlcjY1OTQ0NzE3","is_bot":false,"login":"klai890","name":"Karena Lai"},"headRefName":"kl-paginate-jobs-backend","number":29,"title":"Paginate the Jobs backend","url":"https://github.com/ucsb-cs156-s25/proj-courses-s25-03/pull/29"},{"author":{"id":"U_kgDODDnxkQ","is_bot":false,"login":"ilandry-ucsb","name":""},"headRefName":"il-create-placeholder-page-for-enrollement-data-point","number":28,"title":"Il create placeholder page for enrollement data point","url":"https://github.com/ucsb-cs156-s25/proj-courses-s25-03/pull/28"}]
