
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/proj-courses-s25-03
owner: ucsb-cs156-s25
repo_name: proj-courses-s25-03
pull_requests: [{"author":{"id":"U_kgDOCNntvg","is_bot":false,"login":"kwilliams812","name":"Kade Williams"},"headRefName":"KW-CreateDropdownForClassroomNumbers","number":58,"title":"KW - Create dropdown for classroom numbers","url":"https://github.com/ucsb-cs156-s25/proj-courses-s25-03/pull/58"},{"author":{"id":"U_kgDOB2-VXA","is_bot":false,"login":"daisyzhongg","name":""},"headRefName":"dz-implement-weekly-view-table","number":56,"title":"Implement weekly view table","url":"https://github.com/ucsb-cs156-s25/proj-courses-s25-03/pull/56"},{"author":{"id":"U_kgDODDnxkQ","is_bot":false,"login":"ilandry-ucsb","name":""},"headRefName":"il-change-enrollment-data-fixtures-to-have-different-titles-for-each-data-point","number":55,"title":"Il change enrollment data fixtures to have sample data from different classes","url":"https://github.com/ucsb-cs156-s25/proj-courses-s25-03/pull/55"}]
